version: '3.8'

services:
  mongo:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nodeapp:
    image: vasilii31/lab2:0.2
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    restart: unless-stopped
    pull_policy: always
    
volumes:
  mongo_data:
